name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: asfsafs
      id: asfsafs
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: asfsafs
        setup-command: ''
        command: run.sh
        timeout: 10
    - name: sadfsfdsfsdf
      id: sadfsfdsfsdf
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: sadfsfdsfsdf
        setup-command: ''
        command: gradle test
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        ASFSAFS_RESULTS: "${{steps.asfsafs.outputs.result}}"
        SADFSFDSFSDF_RESULTS: "${{steps.sadfsfdsfsdf.outputs.result}}"
      with:
        runners: asfsafs,sadfsfdsfsdf
